backend:
  name: git-gateway
  branch: main

media_folder: "Logos"
public_folder: "Logos"

collections:
  - name: "catalog"
    label: "Catálogo de Zapatos"
    folder: "content/shoes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Modelo", name: "title", widget: "string" }
      - { label: "Referencia", name: "reference", widget: "string" }
      - { label: "Foto Principal", name: "image", widget: "image" }
      - { label: "Precio / Descripción", name: "description", widget: "text" }
      - { label: "Tallas Disponibles", name: "sizes", widget: "list" }
